name: Scribe Inc.
description: The Scribe development blog.
url: http://scribenet.github.io/

markdown: redcarpet
highlighter: true
encoding: utf-8
timezone: America/New_York

exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock